- name: Deploy static site on nginx in docker
  hosts: web
  become: false
  tasks:
    - name: ensure nginx cont is running
      docker_container:
        name: nginx
        image: nginx:alpine
        state: started
        restart_policy: always
        published_ports:
          - "8080:80"
        volumes:
          - "{{ playbook_dir }}/../site:/usr/share/nginx/html:ro" 

